services:
  openalgo:
    image: openalgo:latest
    build:
      context: .
      dockerfile: Dockerfile

    container_name: openalgo-web
    ports:
      - "${FLASK_PORT:-5000}:5000"
      - "${WEBSOCKET_PORT:-8765}:8765"

    # persistent DB, logs + mount the host .env read-only so dotenv can read it
    volumes:
      - openalgo_db:/app/db
      - openalgo_logs:/app/logs          # Use named volume for logs
      - ./log:/app/log                   # ← Application logs
      - ./strategies:/app/strategies     # ← Python strategies (MAIN FIX)
      - ./keys:/app/keys                 # ← API keys/certificates
      - ./.env:/app/.env:ro

    # (optional) extra env-vars that are NOT in .env
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_DEBUG=${FLASK_DEBUG:-0}

    restart: unless-stopped

# Define named volumes for database and logs persistence
volumes:
  openalgo_db:
    driver: local
  openalgo_logs:
    driver: local
